export const PERIODIZATION_SCHEMES = [
  {
    id: 1,
    name: 'Progressiva — Iniciante',
    level: 'iniciante',
    style: 'progressiva',
    objective: 'Adaptação e progressão gradual',
    total_weeks: 9,
    type: 'weekly',
    configs: [
      { week: 1, phase: 'BASE', phase_color: '#3B82F6', sets: 2, reps_min: 12, reps_max: 12, drop_sets: 0, description: 'Adaptação da técnica' },
      { week: 2, phase: 'BASE', phase_color: '#3B82F6', sets: 3, reps_min: 12, reps_max: 12, drop_sets: 0, description: 'Adaptação da técnica' },
      { week: 3, phase: 'INTENSIF.', phase_color: '#22C55E', sets: 3, reps_min: 10, reps_max: 12, drop_sets: 0, description: 'Progressão de carga' },
      { week: 4, phase: 'INTENSIF.', phase_color: '#22C55E', sets: 3, reps_min: 10, reps_max: 10, drop_sets: 0, description: 'Carga igual / progressão de carga' },
      { week: 5, phase: 'INTENSIF.', phase_color: '#22C55E', sets: 3, reps_min: 8, reps_max: 10, drop_sets: 0, description: 'Progressão de carga' },
      { week: 6, phase: 'INTENSIF.', phase_color: '#22C55E', sets: 3, reps_min: 8, reps_max: 10, drop_sets: 0, description: 'Carga igual' },
      { week: 7, phase: 'RESISTÊNCIA', phase_color: '#6B7280', sets: 3, reps_min: 10, reps_max: 12, drop_sets: 0, description: 'Resistência' },
      { week: 8, phase: 'RESISTÊNCIA', phase_color: '#6B7280', sets: 3, reps_min: 12, reps_max: 15, drop_sets: 0, description: 'Resistência' },
      { week: 9, phase: 'INTENSIF.', phase_color: '#22C55E', sets: 3, reps_min: 8, reps_max: 10, drop_sets: 0, description: 'Progressão de carga' },
    ],
  },
  {
    id: 2,
    name: 'Ondulatória — Iniciante',
    level: 'iniciante',
    style: 'ondulatoria',
    objective: 'Variação de estímulos para iniciantes',
    total_weeks: 9,
    type: 'weekly',
    configs: [
      { week: 1, phase: 'BASE', phase_color: '#3B82F6', sets: 2, reps_min: 12, reps_max: 12, drop_sets: 0, description: 'Adaptação da técnica' },
      { week: 2, phase: 'INTENSIF.', phase_color: '#22C55E', sets: 3, reps_min: 10, reps_max: 12, drop_sets: 0, description: 'Progressão de carga moderada' },
      { week: 3, phase: 'RESISTÊNCIA', phase_color: '#6B7280', sets: 3, reps_min: 12, reps_max: 15, drop_sets: 0, description: 'Mantém carga — mais reps' },
      { week: 4, phase: 'INTENSIF.', phase_color: '#22C55E', sets: 3, reps_min: 8, reps_max: 10, drop_sets: 0, description: 'Progressão de carga' },
      { week: 5, phase: 'RESISTÊNCIA', phase_color: '#6B7280', sets: 3, reps_min: 10, reps_max: 12, drop_sets: 0, description: 'Mantém carga — mais reps' },
      { week: 6, phase: 'INTENSIF.', phase_color: '#22C55E', sets: 3, reps_min: 8, reps_max: 10, drop_sets: 0, description: 'Progressão de carga' },
      { week: 7, phase: 'INTENSIF.', phase_color: '#22C55E', sets: 3, reps_min: 8, reps_max: 10, drop_sets: 0, description: 'Mantém carga' },
      { week: 8, phase: 'RESISTÊNCIA', phase_color: '#6B7280', sets: 3, reps_min: 12, reps_max: 15, drop_sets: 0, description: 'Mantém carga — mais reps' },
      { week: 9, phase: 'INTENSIF.', phase_color: '#22C55E', sets: 3, reps_min: 8, reps_max: 8, drop_sets: 0, description: 'Progressão de carga' },
    ],
  },
  {
    id: 3,
    name: 'Progressiva — Intermediário',
    level: 'intermediario',
    style: 'progressiva',
    objective: 'Progressão com fases de choque',
    total_weeks: 9,
    type: 'weekly',
    configs: [
      { week: 1, phase: 'BASE', phase_color: '#3B82F6', sets: 3, reps_min: 12, reps_max: 12, drop_sets: 0, description: 'Adaptação da técnica' },
      { week: 2, phase: 'BASE', phase_color: '#3B82F6', sets: 3, reps_min: 10, reps_max: 12, drop_sets: 0, description: 'Progressão de carga' },
      { week: 3, phase: 'INTENSIF.', phase_color: '#22C55E', sets: 3, reps_min: 8, reps_max: 10, drop_sets: 0, description: 'Progressão' },
      { week: 4, phase: 'INTENSIF.', phase_color: '#22C55E', sets: 3, reps_min: 8, reps_max: 10, drop_sets: 0, description: 'Mantém carga' },
      { week: 5, phase: 'CHOQUE', phase_color: '#F97316', sets: 4, reps_min: 8, reps_max: 10, drop_sets: 0, description: 'Progressão de carga' },
      { week: 6, phase: 'CHOQUE', phase_color: '#F97316', sets: 4, reps_min: 8, reps_max: 8, drop_sets: 0, description: 'Progressão de carga' },
      { week: 7, phase: 'CHOQUE', phase_color: '#EF4444', sets: 4, reps_min: 9, reps_max: 11, drop_sets: 0, description: 'Mantém carga' },
      { week: 8, phase: 'DELOAD', phase_color: '#A855F7', sets: 3, reps_min: 12, reps_max: 12, drop_sets: 0, description: 'Período regenerativo — redução de carga' },
      { week: 9, phase: 'CHOQUE', phase_color: '#F97316', sets: 4, reps_min: 8, reps_max: 8, drop_sets: 0, description: 'Progressão de carga (maior que sem. 7)' },
    ],
  },
  {
    id: 4,
    name: 'Ondulatória — Intermediário',
    level: 'intermediario',
    style: 'ondulatoria',
    objective: 'Ondulação com choque e deload',
    total_weeks: 9,
    type: 'weekly',
    configs: [
      { week: 1, phase: 'BASE', phase_color: '#3B82F6', sets: 3, reps_min: 12, reps_max: 12, drop_sets: 0, description: 'Adaptação técnica' },
      { week: 2, phase: 'INTENSIF.', phase_color: '#22C55E', sets: 3, reps_min: 10, reps_max: 12, drop_sets: 0, description: 'Progressão de carga' },
      { week: 3, phase: 'CHOQUE', phase_color: '#F97316', sets: 4, reps_min: 8, reps_max: 10, drop_sets: 0, description: 'Progressão de carga' },
      { week: 4, phase: 'CHOQUE+', phase_color: '#F97316', sets: 4, reps_min: 8, reps_max: 8, drop_sets: 0, description: 'Mantém carga' },
      { week: 5, phase: 'CHOQUE', phase_color: '#EF4444', sets: 4, reps_min: 6, reps_max: 8, drop_sets: 0, description: 'Progressão de carga — força pura' },
      { week: 6, phase: 'DELOAD', phase_color: '#A855F7', sets: 3, reps_min: 12, reps_max: 12, drop_sets: 0, description: 'Redução de carga' },
      { week: 7, phase: 'CHOQUE+', phase_color: '#EF4444', sets: 4, reps_min: 9, reps_max: 11, drop_sets: 0, description: 'Resistência — mantém carga da sem. 5' },
      { week: 8, phase: 'CHOQUE+', phase_color: '#EF4444', sets: 4, reps_min: 6, reps_max: 8, drop_sets: 0, description: 'Força pura — progressão de carga' },
      { week: 9, phase: 'CHOQUE+', phase_color: '#EF4444', sets: 4, reps_min: 9, reps_max: 11, drop_sets: 0, description: 'Resistência — mantém carga da sem. 8' },
    ],
  },
  {
    id: 5,
    name: 'Progressiva — Avançado',
    level: 'avancado',
    style: 'progressiva',
    objective: 'Progressão intensa com drop-set e choque+',
    total_weeks: 9,
    type: 'weekly',
    configs: [
      { week: 1, phase: 'BASE', phase_color: '#3B82F6', sets: 3, reps_min: 12, reps_max: 12, drop_sets: 0, description: 'Adaptação da técnica' },
      { week: 2, phase: 'BASE', phase_color: '#3B82F6', sets: 4, reps_min: 10, reps_max: 12, drop_sets: 0, description: 'Adaptação da técnica' },
      { week: 3, phase: 'INTENSIF.', phase_color: '#22C55E', sets: 4, reps_min: 8, reps_max: 10, drop_sets: 0, description: 'Progressão de carga' },
      { week: 4, phase: 'INTENSIF.', phase_color: '#22C55E', sets: 4, reps_min: 8, reps_max: 10, drop_sets: 0, description: 'Mantém carga' },
      { week: 5, phase: 'CHOQUE', phase_color: '#F97316', sets: 4, reps_min: 8, reps_max: 8, drop_sets: 1, description: 'Progressão de carga + drop-set' },
      { week: 6, phase: 'CHOQUE', phase_color: '#F97316', sets: 4, reps_min: 9, reps_max: 11, drop_sets: 0, description: 'Resistência' },
      { week: 7, phase: 'CHOQUE+', phase_color: '#EF4444', sets: 4, reps_min: 6, reps_max: 8, drop_sets: 0, description: 'Progressão de carga' },
      { week: 8, phase: 'CHOQUE+', phase_color: '#EF4444', sets: 4, reps_min: 6, reps_max: 8, drop_sets: 0, description: 'Mantém carga' },
      { week: 9, phase: 'CHOQUE+', phase_color: '#EF4444', sets: 4, reps_min: 9, reps_max: 11, drop_sets: 0, description: 'Mantém carga' },
    ],
  },
  {
    id: 6,
    name: 'Ondulatória — Avançado',
    level: 'avancado',
    style: 'ondulatoria',
    objective: 'Máxima variação com deload estratégico',
    total_weeks: 10,
    type: 'weekly',
    configs: [
      { week: 1, phase: 'BASE', phase_color: '#3B82F6', sets: 4, reps_min: 12, reps_max: 12, drop_sets: 0, description: 'Adaptação da técnica' },
      { week: 2, phase: 'INTENSIF.', phase_color: '#22C55E', sets: 4, reps_min: 10, reps_max: 12, drop_sets: 0, description: 'Progressão de carga' },
      { week: 3, phase: 'INTENSIF.', phase_color: '#22C55E', sets: 4, reps_min: 10, reps_max: 12, drop_sets: 0, description: 'Mantém carga' },
      { week: 4, phase: 'CHOQUE', phase_color: '#F97316', sets: 4, reps_min: 8, reps_max: 8, drop_sets: 0, description: 'Progressão de carga' },
      { week: 5, phase: 'CHOQUE', phase_color: '#EF4444', sets: 4, reps_min: 6, reps_max: 8, drop_sets: 0, description: 'Progressão de carga — força pura' },
      { week: 6, phase: 'CHOQUE+', phase_color: '#EF4444', sets: 4, reps_min: 9, reps_max: 11, drop_sets: 0, description: 'Resistência' },
      { week: 7, phase: 'DELOAD', phase_color: '#A855F7', sets: 3, reps_min: 12, reps_max: 12, drop_sets: 0, description: 'Regenerativo' },
      { week: 8, phase: 'INTENSIF.', phase_color: '#22C55E', sets: 4, reps_min: 8, reps_max: 10, drop_sets: 0, description: 'Progressão de carga' },
      { week: 9, phase: 'CHOQUE', phase_color: '#EF4444', sets: 4, reps_min: 6, reps_max: 8, drop_sets: 0, description: 'Progressão de carga — força pura' },
      { week: 10, phase: 'CHOQUE+', phase_color: '#EF4444', sets: 4, reps_min: 9, reps_max: 11, drop_sets: 0, description: 'Resistência' },
    ],
  },
]
