// In-memory data store — replaces V4's MOCK_DATA global
// Services read/write this. Will be replaced by TanStack Query in Phase 2.
export const store = {
  users: [],
  muscle_groups: [
    { id: 1, name: 'Peito', icon: 'chest' },
    { id: 2, name: 'Costas', icon: 'back' },
    { id: 3, name: 'Quadríceps', icon: 'quads' },
    { id: 4, name: 'Ombros', icon: 'shoulders' },
    { id: 5, name: 'Bíceps', icon: 'biceps' },
    { id: 6, name: 'Tríceps', icon: 'triceps' },
    { id: 7, name: 'Glúteo', icon: 'glutes' },
    { id: 8, name: 'Posterior de Coxa', icon: 'hamstrings' },
    { id: 9, name: 'Panturrilha', icon: 'calves' },
    { id: 10, name: 'Cardio', icon: 'cardio' },
    { id: 11, name: 'Core', icon: 'core' },
  ],
  exercises: [
    { id: 1, name: 'Supino Reto', muscle_group_id: 1, description: 'Exercício fundamental para peito' },
    { id: 2, name: 'Supino Inclinado', muscle_group_id: 1, description: 'Foco na parte superior do peito' },
    { id: 3, name: 'Rosca Direta', muscle_group_id: 5, description: 'Isolamento de bíceps' },
    { id: 4, name: 'Rosca Inversa', muscle_group_id: 5, description: 'Bíceps e antebraço' },
    { id: 5, name: 'Tríceps Corda', muscle_group_id: 6, description: 'Isolamento de tríceps' },
    { id: 6, name: 'Mergulho', muscle_group_id: 6, description: 'Tríceps, ombro e peito' },
    { id: 7, name: 'Puxada Lateral', muscle_group_id: 2, description: 'Exercício de costas composto' },
    { id: 8, name: 'Remada Baixa', muscle_group_id: 2, description: 'Costas e bíceps' },
    { id: 9, name: 'Barra Fixa', muscle_group_id: 2, description: 'Exercício fundamental de costas' },
    { id: 10, name: 'Leg Press', muscle_group_id: 3, description: 'Exercício fundamental para quadríceps' },
    { id: 11, name: 'Agachamento Livre', muscle_group_id: 3, description: 'Movimento composto de quadríceps' },
    { id: 12, name: 'Extensora', muscle_group_id: 3, description: 'Isolamento de quadríceps' },
    { id: 13, name: 'Flexora', muscle_group_id: 8, description: 'Isolamento de posterior de coxa' },
    { id: 14, name: 'Desenvolvimento', muscle_group_id: 4, description: 'Exercício fundamental de ombros' },
    { id: 15, name: 'Elevação Lateral', muscle_group_id: 4, description: 'Isolamento de ombros' },
    { id: 16, name: 'Hip Thrust', muscle_group_id: 7, description: 'Exercício fundamental para glúteos' },
    { id: 17, name: 'Stiff', muscle_group_id: 8, description: 'Posterior de coxa e glúteos' },
    { id: 18, name: 'Panturrilha em Pé', muscle_group_id: 9, description: 'Gastrocnêmio, foco na panturrilha' },
    { id: 19, name: 'Panturrilha Sentado', muscle_group_id: 9, description: 'Sóleo, foco na panturrilha' },
    { id: 20, name: 'Búlgaro', muscle_group_id: 7, description: 'Glúteo e quadríceps unilateral' },
    { id: 21, name: 'Bike', muscle_group_id: 10, description: 'Bicicleta ergométrica' },
    { id: 22, name: 'Remo', muscle_group_id: 10, description: 'Remo ergômetro' },
    { id: 23, name: 'Transport', muscle_group_id: 10, description: 'Transport / elíptico' },
    { id: 24, name: 'S-Force', muscle_group_id: 10, description: 'S-Force / air bike' },
    { id: 25, name: 'Esteira', muscle_group_id: 10, description: 'Caminhada ou corrida' },
    { id: 26, name: 'Escada', muscle_group_id: 10, description: 'Simulador de escada' },
    { id: 27, name: 'Abdominal Crunch', muscle_group_id: 11, description: 'Abdominal tradicional' },
    { id: 28, name: 'Prancha', muscle_group_id: 11, description: 'Prancha isométrica' },
    { id: 29, name: 'Abdominal Infra', muscle_group_id: 11, description: 'Elevação de pernas' },
    { id: 30, name: 'Russian Twist', muscle_group_id: 11, description: 'Rotação com carga para oblíquos' },
    { id: 31, name: 'Abdominal na Roda', muscle_group_id: 11, description: 'Roda abdominal / ab wheel' },
  ],
  templates: [],
  template_plans: [],
  template_exercises: [],
  template_week_configs: [],
  training_phases: [],
  training_plans: [],
  plan_exercises: [],
  week_configs: [],
  workout_sessions: [],
  session_logs: [],
}
